name: frost_guard
description: Eine App, die vor Nachtfrost warnt

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  geolocator: ^10.0.0
  geolocator_android: ^4.4.0
  geocoding: ^2.1.0
  # flutter_local_notifications: ^13.0.0  # Temporär auskommentiert
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_native_splash: ^2.3.1
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
