name: frost_guard
description: Eine App, die vor Nachtfrost warnt

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  shared_preferences: ^2.5.2
  geolocator: ^10.1.0
  geolocator_android: ^4.4.0
  geocoding: ^2.2.0
  flutter_local_notifications: ^18.0.1
  flutter_local_notifications_linux: ^5.0.0
  flutter_local_notifications_platform_interface: ^8.0.0
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  timezone: ^0.9.2
  geolocator_apple: ^2.3.9
  background_fetch: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
